sudo: false

language: python

dist: xenial

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3

install:
  - pip install tox-travis

script:
  - tox

addons:
  apt:
    packages:
    - libenchant-dev

git:
  depth: false
